<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Air extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Tbl_air_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','air/tbl_air_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Tbl_air_model->json();
    }

    public function read($id) 
    {
        $row = $this->Tbl_air_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_air' => $row->id_air,
		'air' => $row->air,
		'bobot' => $row->bobot,
	    );
            $this->template->load('template','air/tbl_air_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('air'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('air/create_action'),
	    'id_air' => set_value('id_air'),
	    'air' => set_value('air'),
	    'bobot' => set_value('bobot'),
	);
        $this->template->load('template','air/tbl_air_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'air' => $this->input->post('air',TRUE),
		'bobot' => $this->input->post('bobot',TRUE),
	    );

            $this->Tbl_air_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('air'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tbl_air_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('air/update_action'),
		'id_air' => set_value('id_air', $row->id_air),
		'air' => set_value('air', $row->air),
		'bobot' => set_value('bobot', $row->bobot),
	    );
            $this->template->load('template','air/tbl_air_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('air'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_air', TRUE));
        } else {
            $data = array(
		'air' => $this->input->post('air',TRUE),
		'bobot' => $this->input->post('bobot',TRUE),
	    );

            $this->Tbl_air_model->update($this->input->post('id_air', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('air'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tbl_air_model->get_by_id($id);

        if ($row) {
            $this->Tbl_air_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('air'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('air'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('air', 'air', 'trim|required');
	$this->form_validation->set_rules('bobot', 'bobot', 'trim|required');

	$this->form_validation->set_rules('id_air', 'id_air', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Air.php */
/* Location: ./application/controllers/Air.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-12 13:53:07 */
/* http://harviacode.com */