<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Gaji extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Tbl_gaji_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','gaji/tbl_gaji_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Tbl_gaji_model->json();
    }

    public function read($id) 
    {
        $row = $this->Tbl_gaji_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_gaji' => $row->id_gaji,
		'gaji' => $row->gaji,
		'bobot' => $row->bobot,
	    );
            $this->template->load('template','gaji/tbl_gaji_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('gaji'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('gaji/create_action'),
	    'id_gaji' => set_value('id_gaji'),
	    'gaji' => set_value('gaji'),
	    'bobot' => set_value('bobot'),
	);
        $this->template->load('template','gaji/tbl_gaji_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'gaji' => $this->input->post('gaji',TRUE),
		'bobot' => $this->input->post('bobot',TRUE),
	    );

            $this->Tbl_gaji_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('gaji'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tbl_gaji_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('gaji/update_action'),
		'id_gaji' => set_value('id_gaji', $row->id_gaji),
		'gaji' => set_value('gaji', $row->gaji),
		'bobot' => set_value('bobot', $row->bobot),
	    );
            $this->template->load('template','gaji/tbl_gaji_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('gaji'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_gaji', TRUE));
        } else {
            $data = array(
		'gaji' => $this->input->post('gaji',TRUE),
		'bobot' => $this->input->post('bobot',TRUE),
	    );

            $this->Tbl_gaji_model->update($this->input->post('id_gaji', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('gaji'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tbl_gaji_model->get_by_id($id);

        if ($row) {
            $this->Tbl_gaji_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('gaji'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('gaji'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('gaji', 'gaji', 'trim|required');
	$this->form_validation->set_rules('bobot', 'bobot', 'trim|required');

	$this->form_validation->set_rules('id_gaji', 'id_gaji', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Gaji.php */
/* Location: ./application/controllers/Gaji.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-12 13:53:20 */
/* http://harviacode.com */