<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Listrik extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Tbl_listrik_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','listrik/tbl_listrik_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Tbl_listrik_model->json();
    }

    public function read($id) 
    {
        $row = $this->Tbl_listrik_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_listrik' => $row->id_listrik,
		'listrik' => $row->listrik,
		'bobot' => $row->bobot,
	    );
            $this->template->load('template','listrik/tbl_listrik_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('listrik'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('listrik/create_action'),
	    'id_listrik' => set_value('id_listrik'),
	    'listrik' => set_value('listrik'),
	    'bobot' => set_value('bobot'),
	);
        $this->template->load('template','listrik/tbl_listrik_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'listrik' => $this->input->post('listrik',TRUE),
		'bobot' => $this->input->post('bobot',TRUE),
	    );

            $this->Tbl_listrik_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('listrik'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tbl_listrik_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('listrik/update_action'),
		'id_listrik' => set_value('id_listrik', $row->id_listrik),
		'listrik' => set_value('listrik', $row->listrik),
		'bobot' => set_value('bobot', $row->bobot),
	    );
            $this->template->load('template','listrik/tbl_listrik_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('listrik'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_listrik', TRUE));
        } else {
            $data = array(
		'listrik' => $this->input->post('listrik',TRUE),
		'bobot' => $this->input->post('bobot',TRUE),
	    );

            $this->Tbl_listrik_model->update($this->input->post('id_listrik', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('listrik'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tbl_listrik_model->get_by_id($id);

        if ($row) {
            $this->Tbl_listrik_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('listrik'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('listrik'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('listrik', 'listrik', 'trim|required');
	$this->form_validation->set_rules('bobot', 'bobot', 'trim|required');

	$this->form_validation->set_rules('id_listrik', 'id_listrik', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Listrik.php */
/* Location: ./application/controllers/Listrik.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-12 13:53:37 */
/* http://harviacode.com */