<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Petugas extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Tbl_petugas_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','petugas/tbl_petugas_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Tbl_petugas_model->json();
    }

    public function read($id) 
    {
        $row = $this->Tbl_petugas_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_petugas' => $row->id_petugas,
		'nama_petugas' => $row->nama_petugas,
		'jabatan' => $row->jabatan,
	    );
            $this->template->load('template','petugas/tbl_petugas_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('petugas'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('petugas/create_action'),
	    'id_petugas' => set_value('id_petugas'),
	    'nama_petugas' => set_value('nama_petugas'),
	    'jabatan' => set_value('jabatan'),
	);
        $this->template->load('template','petugas/tbl_petugas_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_petugas' => $this->input->post('nama_petugas',TRUE),
		'jabatan' => $this->input->post('jabatan',TRUE),
	    );

            $this->Tbl_petugas_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('petugas'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tbl_petugas_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('petugas/update_action'),
		'id_petugas' => set_value('id_petugas', $row->id_petugas),
		'nama_petugas' => set_value('nama_petugas', $row->nama_petugas),
		'jabatan' => set_value('jabatan', $row->jabatan),
	    );
            $this->template->load('template','petugas/tbl_petugas_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('petugas'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_petugas', TRUE));
        } else {
            $data = array(
		'nama_petugas' => $this->input->post('nama_petugas',TRUE),
		'jabatan' => $this->input->post('jabatan',TRUE),
	    );

            $this->Tbl_petugas_model->update($this->input->post('id_petugas', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('petugas'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tbl_petugas_model->get_by_id($id);

        if ($row) {
            $this->Tbl_petugas_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('petugas'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('petugas'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_petugas', 'nama petugas', 'trim|required');
	$this->form_validation->set_rules('jabatan', 'jabatan', 'trim|required');

	$this->form_validation->set_rules('id_petugas', 'id_petugas', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Petugas.php */
/* Location: ./application/controllers/Petugas.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-12 13:46:02 */
/* http://harviacode.com */