<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Rumah extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Tbl_rumah_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','rumah/tbl_rumah_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Tbl_rumah_model->json();
    }

    public function read($id) 
    {
        $row = $this->Tbl_rumah_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_rumah' => $row->id_rumah,
		'luas_rumah' => $row->luas_rumah,
		'bobot' => $row->bobot,
	    );
            $this->template->load('template','rumah/tbl_rumah_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('rumah'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('rumah/create_action'),
	    'id_rumah' => set_value('id_rumah'),
	    'luas_rumah' => set_value('luas_rumah'),
	    'bobot' => set_value('bobot'),
	);
        $this->template->load('template','rumah/tbl_rumah_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'luas_rumah' => $this->input->post('luas_rumah',TRUE),
		'bobot' => $this->input->post('bobot',TRUE),
	    );

            $this->Tbl_rumah_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('rumah'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tbl_rumah_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('rumah/update_action'),
		'id_rumah' => set_value('id_rumah', $row->id_rumah),
		'luas_rumah' => set_value('luas_rumah', $row->luas_rumah),
		'bobot' => set_value('bobot', $row->bobot),
	    );
            $this->template->load('template','rumah/tbl_rumah_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('rumah'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_rumah', TRUE));
        } else {
            $data = array(
		'luas_rumah' => $this->input->post('luas_rumah',TRUE),
		'bobot' => $this->input->post('bobot',TRUE),
	    );

            $this->Tbl_rumah_model->update($this->input->post('id_rumah', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('rumah'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tbl_rumah_model->get_by_id($id);

        if ($row) {
            $this->Tbl_rumah_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('rumah'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('rumah'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('luas_rumah', 'luas rumah', 'trim|required');
	$this->form_validation->set_rules('bobot', 'bobot', 'trim|required');

	$this->form_validation->set_rules('id_rumah', 'id_rumah', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Rumah.php */
/* Location: ./application/controllers/Rumah.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-12 13:53:54 */
/* http://harviacode.com */