<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tanggungan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Tbl_tanggungan_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','tanggungan/tbl_tanggungan_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Tbl_tanggungan_model->json();
    }

    public function read($id) 
    {
        $row = $this->Tbl_tanggungan_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_tanggungan' => $row->id_tanggungan,
		'jumlah_tanggungan' => $row->jumlah_tanggungan,
		'bobot' => $row->bobot,
	    );
            $this->template->load('template','tanggungan/tbl_tanggungan_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tanggungan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('tanggungan/create_action'),
	    'id_tanggungan' => set_value('id_tanggungan'),
	    'jumlah_tanggungan' => set_value('jumlah_tanggungan'),
	    'bobot' => set_value('bobot'),
	);
        $this->template->load('template','tanggungan/tbl_tanggungan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'jumlah_tanggungan' => $this->input->post('jumlah_tanggungan',TRUE),
		'bobot' => $this->input->post('bobot',TRUE),
	    );

            $this->Tbl_tanggungan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('tanggungan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tbl_tanggungan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('tanggungan/update_action'),
		'id_tanggungan' => set_value('id_tanggungan', $row->id_tanggungan),
		'jumlah_tanggungan' => set_value('jumlah_tanggungan', $row->jumlah_tanggungan),
		'bobot' => set_value('bobot', $row->bobot),
	    );
            $this->template->load('template','tanggungan/tbl_tanggungan_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tanggungan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_tanggungan', TRUE));
        } else {
            $data = array(
		'jumlah_tanggungan' => $this->input->post('jumlah_tanggungan',TRUE),
		'bobot' => $this->input->post('bobot',TRUE),
	    );

            $this->Tbl_tanggungan_model->update($this->input->post('id_tanggungan', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('tanggungan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tbl_tanggungan_model->get_by_id($id);

        if ($row) {
            $this->Tbl_tanggungan_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('tanggungan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tanggungan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('jumlah_tanggungan', 'jumlah tanggungan', 'trim|required');
	$this->form_validation->set_rules('bobot', 'bobot', 'trim|required');

	$this->form_validation->set_rules('id_tanggungan', 'id_tanggungan', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Tanggungan.php */
/* Location: ./application/controllers/Tanggungan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-12 13:54:10 */
/* http://harviacode.com */