<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_warga_model extends CI_Model
{

    public $table = 'tbl_warga';
    public $id = 'id_warga';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_warga,no_kk,nik_warga,nama_kk,tempat_lahir,tanggal_lahir,jenis_kelamin,alamat,agama,pekerjaan');
        $this->datatables->from('tbl_warga');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_warga.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('warga/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('warga/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('warga/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_warga');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_warga', $q);
	$this->db->or_like('no_kk', $q);
	$this->db->or_like('nik_warga', $q);
	$this->db->or_like('nama_kk', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('pekerjaan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_warga', $q);
	$this->db->or_like('no_kk', $q);
	$this->db->or_like('nik_warga', $q);
	$this->db->or_like('nama_kk', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('pekerjaan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_warga_model.php */
/* Location: ./application/models/Tbl_warga_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-12 13:38:42 */
/* http://harviacode.com */